### ISSUE TITLE
Implement Sass syntax choice

### ISSUE THREAD

**Issue by larsonjj** [larsonjj/generator-yeogurt#52]
By default, the Scss syntax is used when using Sass. This is a proposal for being able to use the "white-space" dependent syntax variant of Sass is desired.

**Proposed**

``` sass
// Sass Syntax

body
  font: 100% Helvetica, sans-serif
  background-color: #efefef
```

**Default**

``` scss
// Scss Syntax

body {
  font: 100% Helvetica, sans-serif;
  background-color: #efefef;
}
```

It would be beneficial to allow a user to choose what type of Sass syntax they would like.

Changes needed:
- Change file comment from JSDoc format to simple  double slashes `//`
- File extension becomes `.sass`
